### ISSUE TITLE
Jobs failing on travis-ci

### ISSUE THREAD

**Issue by kishorkunal-raj** [ierror/django-js-reverse#100]
Hi All,

I am trying to run jobs on intel architecture, but few jobs are failing.  logs are as follows

$ tox
py35-django22 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django22
py35-django22 installdeps: coverage==4.5.1, js2py==0.63, Django>=2.2,<2.23
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django22/log/py35-django22-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<2.23,>=2.2
  Using cached https://files.pythonhosted.org/packages/06/30/3b7e846c1a2f5435f52c408442e09c0c35ca6fa1c4abbad0ccf4d42fb172/Django-2.2.16-py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting pytz (from Django<2.23,>=2.2)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting sqlparse>=0.2.2 (from Django<2.23,>=2.2)
  Using cached https://files.pythonhosted.org/packages/10/96/36c136013c4a6ecb8c6aa3eed66e6dcea838f85fd80e1446499f1dabfac7/sqlparse-0.4.0-py3-none-any.whl
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.2,<2.23]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django22/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.2,<2.23'", 1)
py35-django21 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django21
py35-django21 installdeps: coverage==4.5.1, js2py==0.63, Django>=2.1,<2.2
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django21/log/py35-django21-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<2.2,>=2.1
  Using cached https://files.pythonhosted.org/packages/ff/82/55a696532518aa47666b45480b579a221638ab29d60d33ce71fcbd3cef9a/Django-2.1.15-py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting pytz (from Django<2.2,>=2.1)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.1,<2.2]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django21/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.1,<2.2'", 1)
py35-django20 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django20
py35-django20 installdeps: coverage==4.5.1, js2py==0.63, Django>=2.0,<2.1
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django20/log/py35-django20-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<2.1,>=2.0
  Using cached https://files.pythonhosted.org/packages/67/b0/64645bd6c5cdabb07d361e568eecfa9e64027ae4cb4778bb00be8c4bde00/Django-2.0.13-py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting pytz (from Django<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.0,<2.1]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django20/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.0,<2.1'", 1)
py35-django111 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django111
py35-django111 installdeps: coverage==4.5.1, js2py==0.63, Django>=1.11,<1.12
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django111/log/py35-django111-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<1.12,>=1.11
  Using cached https://files.pythonhosted.org/packages/49/49/178daa8725d29c475216259eb19e90b2aa0b8c0431af8c7e9b490ae6481d/Django-1.11.29-py2.py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting pytz (from Django<1.12,>=1.11)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.11,<1.12]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django111/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.11,<1.12'", 1)
py35-django110 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django110
py35-django110 installdeps: coverage==4.5.1, js2py==0.63, Django>=1.10,<1.11
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django110/log/py35-django110-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<1.11,>=1.10
  Using cached https://files.pythonhosted.org/packages/bb/9f/2c20639ac635a83123ddffd91ba15001cb0d04e74fbb08f31fb57e490dab/Django-1.10.8-py2.py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.10,<1.11]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django110/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.10,<1.11'", 1)
py35-django19 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django19
py35-django19 installdeps: coverage==4.5.1, js2py==0.63, Django>=1.9,<1.10
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django19/log/py35-django19-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<1.10,>=1.9
  Using cached https://files.pythonhosted.org/packages/a6/ee/6dfd9e8e0d61ab22ed09c6c8f6ae5a4ad0d3bf07bca9124fb5a087f876df/Django-1.9.13-py2.py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.9,<1.10]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django19/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.9,<1.10'", 1)
py35-django18 create: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django18
py35-django18 installdeps: coverage==4.5.1, js2py==0.63, Django>=1.8,<1.9
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django18/log/py35-django18-1.log
================================== log start ===================================
Collecting coverage==4.5.1
  Using cached https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting js2py==0.63
  Using cached https://files.pythonhosted.org/packages/90/ef/c0800fcfa568ee4baa95a7ceec5a33178bac86e6643857f30cf3ddb78933/Js2Py-0.63.tar.gz
Collecting Django<1.9,>=1.8
  Using cached https://files.pythonhosted.org/packages/96/b9/b4108da1275dc2ac1bba1e87739cb31b3d44339affb83b0e949fb09c2bef/Django-1.8.19-py2.py3-none-any.whl
Collecting tzlocal>=1.2 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz
  Requested tzlocal>=1.2 from https://files.pythonhosted.org/packages/79/8c/7d9608dd2643a144bd473405d268973ee1c67aac4c72c4d73910dc8a4754/tzlocal-3.0b1.tar.gz#sha256=efd2821b10836b046fac09c4e31e7b97f45b89e718e82b8bc18a9e424bb2f662 (from js2py==0.63), but installing version 3.0b1
Collecting six>=1.10 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from js2py==0.63)
  Using cached https://files.pythonhosted.org/packages/48/ef/c72abcfa2c6accd03e7c89c400790fc3d908c5804d50a7c4e9ceabd74d23/pyjsparser-2.7.1.tar.gz
Collecting backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
  Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
=================================== log end ====================================
ERROR: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.8,<1.9]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django18/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.8,<1.9'", 1)
___________________________________ summary ____________________________________
ERROR:   py35-django22: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.2,<2.23]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django22/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.2,<2.23'", 1)
ERROR:   py35-django21: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.1,<2.2]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django21/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.1,<2.2'", 1)
ERROR:   py35-django20: could not install deps [coverage==4.5.1, js2py==0.63, Django>=2.0,<2.1]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django20/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=2.0,<2.1'", 1)
ERROR:   py35-django111: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.11,<1.12]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django111/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.11,<1.12'", 1)
ERROR:   py35-django110: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.10,<1.11]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django110/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.10,<1.11'", 1)
ERROR:   py35-django19: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.9,<1.10]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django19/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.9,<1.10'", 1)
ERROR:   py35-django18: could not install deps [coverage==4.5.1, js2py==0.63, Django>=1.8,<1.9]; v = InvocationError("/home/travis/build/kishorkunal-raj/django-js-reverse/.tox/py35-django18/bin/python -m pip install --pre coverage==4.5.1 js2py==0.63 'Django>=1.8,<1.9'", 1)
The command "tox" exited with 1.
cache.2
store build cache
Done. Your build exited with 1.

Please help me to fix the issue

**Comment by PeterJCLaw** [comment]
Looks like `js2py`'s dependencies are failing to me? Specifically see the lines:
```
 Could not find a version that satisfies the requirement backports.zoneinfo (from tzlocal>=1.2->js2py==0.63) (from versions: )
No matching distribution found for backports.zoneinfo (from tzlocal>=1.2->js2py==0.63)
```
Which looks like it's probably related to the latest releases of `backports.zoneinfo` not supporting Python < 3.6
