### ISSUE TITLE
Django 4.0 compitability

### ISSUE THREAD

**Issue by miklagard** [ierror/django-js-reverse#108]
django-js-reverse returns following error in Django 4.0

According to release notes of Django 4.0
> django.utils.encoding.force_text() and smart_text() are removed.

Related part in core.py (seems like it was solved already)

    if sys.version_info < (3, ):
        from django.utils.encoding import force_text
    else:
        from django.utils.encoding import force_str as force_text

> django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_js_reverse.templatetags.js_reverse': cannot import name 'force_text' from 'django.utils.encoding' (/home/cem/PycharmProjects/crm_website/website/venv/lib/python3.9/site-packages/django/utils/encoding.py)

**So, that would be perfect if the new pip package will be deployed.**

**Comment by davmlaw** [comment]
Thanks for this project - would really appreciate a release made in Pip so Django 4 works out of the box
