### ISSUE TITLE
Limit the exposed URLs using a white/blacklist

### ISSUE THREAD

**Issue by asser** [ierror/django-js-reverse#13]
It would be great if one was able to limit the URLs exposed in this view to avoid giving away too much information about the URLs available on the site, so only the necessary ones (actually used by Javascript) are shown.

I think it would be impossible to automatically deduce which ones are used by the site's Javascript files, but maybe it would be possible to choose which ones to expose in the urlconfig file.

Any suggestions for the best way to handle this? I'll happily make a patch but not sure about the exact approach.

**Comment by ierror** [comment]
I mereged Andertakes changes an released v0.4.1

**Comment by BrnoPCmaniak** [comment]
I added feature to include only specific namespaces something like whitelist. #34

**Comment by ihabunek** [comment]
This would be a welcome feature, we have dosens of apps and blacklisting them is a pain when I just want to use it for a single app (which is usually the case).
