### ISSUE TITLE
Mapping under suburl doesn't work

### ISSUE THREAD

**Issue by lizter** [ierror/django-js-reverse#25]
I have a page running under a suburl like example.org/foo/

When running manage.py collectstatic_js_reverse, it does not take this into account.

**Comment by ierror** [comment]
Hello lizter, thanks for reporting. I need to dive deeper into this issue the next days. Actually this https://github.com/ierror/django-js-reverse/blob/production/django_js_reverse/views.py#L35 should handle script prefixes.

**Comment by ierror** [comment]
The collectstatic_js_reverse command has no knowledge about the request context. I fixed the issue and built a new release 0.4.5. Set the subpath via **JS_REVERSE_SCRIPT_PREFIX**. thanks again for reporting!
