### ISSUE TITLE
Add more flexible support for including/excluding urls

### ISSUE THREAD

**Issue by mjnaderi** [ierror/django-js-reverse#35]
Hi,

I have added some external apps to my projects, and I want to exclude their urls from django-js-reverse. But the problem is that I cannot put namespace for their urls (When I set namespace, app doesn't work).

For example I have installed `django-simple-captcha` and I have added this to my urls.py:

    url(r'^captcha/', include('captcha.urls')),

I want to exclude this app's urls. But when I change this line to:

    url(r'^captcha/', include('captcha.urls', namespace='captcha')),

the captcha app doesn't work.

A whitelist for urls, or an option to exclude urls base on their prefix will help to solve similar issues.

Maybe:

    EXCLUDE_PREFIXES = ['captcha', '...', ...]

But I think a whitelist does the job better:

    INCLUDE_NAMESPACES = ['app1', 'app2', ...]
    INCLUDE_PREFIXES = ['abc', ...]

**Comment by fedosov** [comment]
:+1:

**Comment by ierror** [comment]
you can now include specific namespaces only, see JS_REVERSE_INCLUDE_ONLY_NAMESPACES setting for details.
