### ISSUE TITLE
Support for {% static %}

### ISSUE THREAD

**Issue by imaia** [ierror/django-js-reverse#39]
It would be very nice to have support for {% static %}. Any plans?

**Comment by ierror** [comment]
What do you mean by "support for {% static %}"? You can include js_reverse within static by using 
`<script src="{% url js_reverse %}" type="text/javascript"></script>`

**Comment by imaia** [comment]
I mean this:

```
Urls.static('img/something.jpg')
```

**Comment by ierror** [comment]
ATM i don't need such access to my static content, but feel free to fork and add a PR :-)

**Comment by imaia** [comment]
Fair enough. Will do. I think this feature would be quite useful for those using angularjs or vue-router (my case).

**Comment by paulshannon** [comment]
@imaia Have you done any work on this? I agree that it would be useful.

**Comment by Valian** [comment]
I'm using vue in my project. I've resolved problem with static files using `collectstatic` preprocessing phase - each static route found in `bundle.js` is replaced with a proper path (i'm using `ManifestStaticFilesStorage`, but you can write your own custom storage)

**Comment by italomaia** [comment]
I did @paulshannon PR on its way.

**Comment by ierror** [comment]
any updates regarding the PR?

**Comment by italomaia** [comment]
Not so far. I confess to have forgotten about it.
