### ISSUE TITLE
URL Regex patterns are ignored

### ISSUE THREAD

**Issue by twheys** [ierror/django-js-reverse#43]
When reversing an overridden URL pattern that use a regex, the regexes are ignored and the last URL is used.  

```
urlpatterns = [
    url(r'^word/(?P<b>\w+)/?$', views.call_word, name='smart_url'),
    url(r'^number/(?P<a>\d+)/?$', views.call_number, name='smart_url'),
]
```

If I call this in Django, the regex is respected and only one URL will match:
`reverse('smart_url', args=['abc'])` results in `word/abc`
`reverse('smart_url', args=[123])` results in `number/123`

In Javascript the regex is overlooked and the last URL with a matching name and number of arguments is used:

`Urls.smart_url('abc')` results in `number/abc` 
`Urls.smart_url(123)`  results in `number/123`

**Comment by alexcasalboni** [comment]
Hey @twheys, I think you just can't use the same name for two different routes. This is not supported by django's own server-side reverse either, afaik.

**Comment by twheys** [comment]
Hi @alexcasalboni, this does indeed work in django's reverse.  I have used it quite a bit in my project, however the overloaded URL patterns do not work in js-reverse because of the regexes.  Overloading based on number of parameters however does seem to work in js-reverse.

**Comment by alexcasalboni** [comment]
I see. I guess the assumption of django-js-reverse is that one route name corresponds to one pattern (given that the mapping is implemented as a plain object/dictionary).

**Comment by ierror** [comment]
I have no idea how to solve this. As far as i can see we would need to translate the Python regex syntax into JavaScript regex to handle such a case? Ideas welcome :-)

**Comment by ierror** [comment]
Some links

- https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines
- http://xregexp.com - could be a way to handle the python regex

**Comment by ierror** [comment]
I'll close this issue for now- IMHO regex support would bring in too much complexity.
