### ISSUE TITLE
Usage as static file does not work with multiple languages

### ISSUE THREAD

**Issue by vladlep** [ierror/django-js-reverse#50]
Hi,

I upgrade the library to the latest to use the ./manage.py collectstatic_js_reverse and load the static file on our servers which is a great feature. 
Unfortunately it does not work for us. If we load the generated file the Urls contain None instead of the language code: 
http://localhost:8000/None/api/v2/costs/

If we used the old cached view loading of the lib it works. 
http://localhost:8000/en/api/v2/costs/
or 
http://localhost:8000/nl/api/v2/costs/
depending on the language of the user. 

Are there some configs that i am missing? 

Thanks,
Vlad

**Comment by ierror** [comment]
Hello Vlad, did you solved the issue?

**Comment by vladlep** [comment]
Hi,

I solved it a while ago but was a bit custom for our case. Did not consider if this way will work in other cases. You can see here the commits I made: 
https://github.com/vladlep/django-js-reverse/commits/develop
