### ISSUE TITLE
PyPI Packaging

### ISSUE THREAD

**Issue by audiolion** [ierror/django-js-reverse#53]
Hello!

The library currently installs the `tests` folder along with the `django_js_reverse` package when installing from PyPI with `pip`. The `tests` folder is installed as a separate folder as well which is a bit awkward as it could namespace clash with a folder name `tests` inside `lib/site-packages` where `pip` installs stuff to

**Comment by ZuluPro** [comment]
I think tests should be included inside the app.
It could helps to write tests using django-js-reverse.

**Comment by audiolion** [comment]
yes included inside the namespace works, as well, but outside the app install is no good

**Comment by ierror** [comment]
fixed in the current v.0.8.1 release, thanks!
