### ISSUE TITLE
Script path not taken into account

### ISSUE THREAD

**Issue by LaundroMat** [ierror/django-js-reverse#56]
Hi,

First of all, thanks for this library, it's a life-saver. I've come across the following issue however.

When in my Django settings, I set e.g.  FORCE_SCRIPT_NAME = "/staging"
then a template tag like {% url 'detail' 1 %} will give me an URL with "staging" prepended. Output is eg /staging/item/1.

But with django-js-reverse, it seems the setting is not taken into account. Urls.detail(1) will give me /item/1. I have set JS_REVERSE_SCRIPT_PREFIX = "/staging" too, but to no avail.

**Comment by LaundroMat** [comment]
I've tested some more, and found that in face the FORCE_SCRIPT_NAME setting is not required for the {% url %} template tag to create the correct URL (i.e. with "staging" prepended). In the same page, using the JS console, Urls.detail(1) does not have the "/staging" part prepended. 

I'm using Django 1.11.4 by the way.

**Comment by msfernandes** [comment]
Maybe you don't need to solve this issue... But there is a settings variable called JS_SCRIPT_PREFIX :)
https://github.com/ierror/django-js-reverse/blob/master/django_js_reverse/js_reverse_settings.py

**Comment by ierror** [comment]
as mentioned JS_SCRIPT_PREFIX should solve the issue
