### ISSUE TITLE
Django 2

### ISSUE THREAD

**Issue by foxmask** [ierror/django-js-reverse#57]
[last release, remove urlsresolvers](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0) and replace by `from django.urls import resolvers` but won't keep
those functions `get_script_prefix`, `set_script_prefix`, and this release won't support python 2 at all.

**Comment by ierror** [comment]
We just released v0.8.1 including Django 2.0 support

**Comment by foxmask** [comment]
thanks for #58
