### ISSUE TITLE
support for webpack

### ISSUE THREAD

**Issue by graingert** [ierror/django-js-reverse#61]
provide an npm module and JSON http api to get the data into it.

**Comment by graingert** [comment]
```
import djangoJSReverse from '@ierror/django-js-reverse';

(async () => {
  const res = await fetch('/urls.json');
  const urlConfig = await res.json();
  const Url = djangoJSReverse(urlConfig);
  ... use Url
})();

**Comment by jamesloewen** [comment]
This package is designed as a management command from python to generate a static file. Generating urls dynamically through an API is strictly worse in this context in terms of complexity and overhead.

**Comment by graingert** [comment]
The json API doesn't have to be dynamic. Could be a management commend to generate it
