### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by douglance** [ierror/django-js-reverse#62]
How does this work with Django URL Paths? 

https://docs.djangoproject.com/en/2.0/ref/urls/#path

**Comment by ierror** [comment]
Should work like the regex based URL patterns:

https://github.com/ierror/django-js-reverse/blob/develop/django_js_reverse/tests/test_urls.py#L48
https://github.com/ierror/django-js-reverse/blob/develop/django_js_reverse/tests/unit_tests.py#L178
