### ISSUE TITLE
The database is required to make export.

### ISSUE THREAD

**Issue by inakrin** [ierror/django-js-reverse#63]
Could you please add requires_system_checks = False to the Command class. 
This will make presence of the database is not required, which is very suitable for CI frontends builds.

**Comment by inakrin** [comment]
I've added it here, but cannot create a pull request for this repo... 
https://github.com/inakrin/django-js-reverse

**Comment by graingert** [comment]
@inakrin do you want to try again at that PR?

**Comment by graingert** [comment]
https://github.com/ierror/django-js-reverse/pull/86 how about that?
