### ISSUE TITLE
ROOT_URLCONF not taken into account

### ISSUE THREAD

**Issue by LuukOost** [ierror/django-js-reverse#73]
If you set the ROOT_URLCONF in settings.py it is not considered by django-js-reverse using the command _python manage.py collectstatic_js_reverse._ 
I would suggest the following change in collectstatic_js_reverse.py to solve this. Replace line 40:
``` 
       default_urlresolver = get_resolver(urlconf)
```
by:
```
        try:
            urlconf = settings.ROOT_URLCONF
        except AttributeError:
            urlconf = None
        default_urlresolver = get_resolver(urlconf)

```

**Comment by ierror** [comment]
Thank you for fixing this issue! @LuukOost @graingert
