### ISSUE TITLE
JS_EXCLUDE_PREFIX

### ISSUE THREAD

**Issue by FrancoisDupont** [ierror/django-js-reverse#78]
Hi,

We have an application with hundreds of urls name, however we would like to exclude some urls which all have the same prefix url address. 

What's do you think about adding a new option like JS_EXCLUDE_PREFIX = ['foo'] which will remove all urls names which contains 'foo' ?

**Comment by ierror** [comment]
setting
> JS_REVERSE_EXCLUDE_NAMESPACES
does not work for you?
