### ISSUE TITLE
move to jazzband

### ISSUE THREAD

**Issue by graingert** [ierror/django-js-reverse#99]
https://github.com/jazzband, It's a great place for Django projects

**Comment by graingert** [comment]
https://github.com/jazzband

**Comment by PeterJCLaw** [comment]
@graingert just wondering whether there's any movement on this and/or getting a new release out?

**Comment by graingert** [comment]
No movement on this :(

**Comment by graingert** [comment]
@ierror can you add me as a repository admin and pypi.org owner so that I can apply for jazzband inclusion and configure automatic releases

**Comment by graingert** [comment]
> @graingert Could you please remove "graingert/django-js-reverse"? Then i will change ownership to you ("graingert/django-js-reverse already exists")

done, thanks!

**Comment by ierror** [comment]
What are the next steps? I can help migrating to jazzband if needed
